---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: default
spec:
  channel: flux-gitops
  secretRef:
    name: discord
  type: discord
  username: FluxBot

